//! OpenAPI 3 document for the Server's HTTP surface.
//!
//! The full document (including the `agent` tag) is exported through the
//! `--print-openapi` CLI for `docs/openapi/openapi.json`; the browser client
//! is generated from a filtered copy that drops `agent` operations and their
//! schemas (design §13.4). Public and Admin routes use independent tags.

use utoipa::Modify;
use utoipa::OpenApi;
use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::openapi::{Components, OpenApi as OpenApiDoc};

use crate::http::health;

/// Document the Agent API's Bearer authentication (design §12.5/§12.6):
/// `POST /api/agent/v1/enroll` authenticates a one-time Enrollment Token
/// (`pp_enroll_…`), every other Agent route an Agent Credential
/// (`pp_agent_…`). Human routes use cookie sessions and must stay
/// unmarked, so the scheme is attached per operation instead of globally.
struct AgentBearerScheme;

impl Modify for AgentBearerScheme {
    fn modify(&self, openapi: &mut OpenApiDoc) {
        openapi.components.get_or_insert_with(Components::new).add_security_scheme(
            "agent_bearer",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("Agent Credential (pp_agent_…) or one-time Enrollment Token (pp_enroll_…)")
                    .description(Some(
                        "Agent API Bearer token. Enrollment exchanges a one-time pp_enroll_… token for an Agent identity; all other Agent routes require the issued pp_agent_… credential.",
                    ))
                    .build(),
            ),
        );

        if let Some(operation) = openapi
            .paths
            .paths
            .get_mut("/api/agent/v1/enroll")
            .and_then(|path| path.post.as_mut())
        {
            operation.security = Some(vec![utoipa::openapi::security::SecurityRequirement::new(
                "agent_bearer",
                Vec::<String>::new(),
            )]);
        }
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        health::live,
        health::ready,
        crate::http::public::login_handler,
        crate::http::public::logout_handler,
        crate::http::public::session_handler,
        crate::http::public::public_networks,
        crate::http::public::public_network,
        crate::http::public::public_node_detail,
        crate::http::public::public_node_history,
        crate::http::public::public_node_peer_history,
        crate::http::public::public_node_history_export,
        crate::http::public::public_validator_history,
        crate::http::public::public_events,
        crate::http::public::public_access_settings,
        crate::http::admin::admin_events,
        crate::http::admin::set_visibility,
        crate::http::admin::set_node_metadata,
        crate::http::admin::admin_nodes,
        crate::http::admin::admin_node_detail,
        crate::http::admin::admin_node_peer_churn,
        crate::http::admin::admin_node_peer_history,
        crate::http::admin::admin_networks,
        crate::http::admin::admin_network_detail,
        crate::http::admin::create_network,
        crate::http::admin::update_network,
        crate::http::admin::diagnostics,
        crate::http::admin::overview,
        crate::http::admin::admin_geo_status,
        crate::http::admin::admin_node_history,
        crate::http::admin::admin_node_transfers,
        crate::http::admin::create_node_transfer,
        crate::http::admin::admin_transfer_detail,
        crate::http::admin::cancel_node_transfer,
        crate::http::admin::admin_agent_detail,
        crate::http::admin::admin_agent_audit,
        crate::http::admin::admin_enrollment_token,
        crate::http::admin::admin_recovery_token,
        crate::http::admin::admin_rotate_credential,
        crate::http::admin::admin_revoke_credential,
        crate::http::validators_admin::admin_validators,
        crate::http::validators_admin::admin_validator_detail,
        crate::http::validators_admin::admin_validator_history,
        crate::http::validators_admin::create_validator,
        crate::http::validators_admin::admin_validator_links,
    crate::http::validators_admin::admin_validator_link_detail,
        crate::http::validators_admin::admin_node_validator_links,
        crate::http::validators_admin::create_node_validator_link,
        crate::http::validators_admin::update_validator_link,
        crate::http::validators_admin::end_validator_link,
        crate::http::access::people_list,
        crate::http::access::create_person,
        crate::http::access::set_person_role,
        crate::http::access::set_person_status,
        crate::http::access::reset_person_password,
        crate::http::access::sessions_list,
        crate::http::access::revoke_session,
        crate::http::access::revoke_other_sessions,
        crate::http::access::audit_list,
        crate::http::access::get_access_settings,
        crate::http::access::set_access_settings,
        crate::http::alerts_admin::alert_rules,
        crate::http::alerts_admin::alert_rule_detail,
        crate::http::alerts_admin::update_alert_rule,
        crate::http::alerts_admin::preview_alert_rule,
        crate::http::alerts_admin::upsert_rule_override,
        crate::http::alerts_admin::delete_rule_override,
        crate::http::alerts_admin::alert_incidents,
        crate::http::alerts_admin::alert_incident_detail,
        crate::http::alerts_admin::alert_silences,
        crate::http::alerts_admin::create_silence,
        crate::http::alerts_admin::alert_silence_detail,
        crate::http::alerts_admin::cancel_silence,
        crate::http::alerts_admin::alert_maintenance,
        crate::http::alerts_admin::create_maintenance_window,
        crate::http::alerts_admin::alert_maintenance_detail,
        crate::http::alerts_admin::cancel_maintenance_window,
        crate::http::notifications_admin::notification_events,
        crate::http::notifications_admin::notification_event_detail,
        crate::http::notifications_admin::notification_deliveries,
        crate::http::notifications_admin::notification_delivery_detail,
        crate::http::notifications_admin::retry_delivery,
        crate::http::notifications_admin::notification_channels,
        crate::http::notifications_admin::notification_channel_detail,
        crate::http::notifications_admin::test_notification_channel,
        crate::http::operations_admin::operations_list,
        crate::http::operations_admin::operation_detail,
        crate::http::operations_admin::cancel_operation,
        crate::http::operations_admin::retention_overview,
        crate::http::operations_admin::retention_impact,
        crate::http::operations_admin::update_retention_policy,
        crate::http::operations_admin::retention_run,
        crate::http::operations_admin::backups_list,
        crate::http::operations_admin::backup_artifact_detail,
        crate::http::operations_admin::backup_create,
        crate::http::operations_admin::backup_verify,
        crate::http::operations_admin::restore_validate,
        crate::http::operations_admin::restore_submit,
        crate::http::operations_admin::doctor_overview,
        crate::http::operations_admin::doctor_run,
        crate::http::agent::enroll_handler,
        crate::http::agent::recover_handler,
    ),
    components(schemas(
        crate::http::ApiErrorBody,
        crate::http::ApiError,
        crate::http::public::LoginRequest,
        crate::http::public::SessionResponse,
        crate::http::public::SessionProjection,
        crate::http::public::PublicNetwork,
        crate::http::public::PublicNode,
        crate::http::public::PublicPeerInsight,
        crate::http::public::PublicCountryCount,
        crate::http::public::PublicGeoInsight,
        crate::http::public::PublicBlockHistoryItem,
        crate::http::public::PublicValidatorHistoryEntry,
        crate::http::public::PublicValidatorHistoryResponse,
        crate::http::public::PublicPeerHistory,
        crate::http::public::PublicPeerAggregate,
        crate::http::public::PublicPeerLagSummary,
        crate::http::admin::VisibilityRequest,
        crate::http::admin::VisibilityResponse,
        crate::http::admin::NodeMetadataRequest,
        crate::http::admin::NodeMetadataResponse,
        crate::http::admin::NodeTransfer,
        crate::http::admin::NodeTransferCreateRequest,
        crate::http::admin::NodeTransferMutationResponse,
        crate::http::admin::AdminNodeListItem,
        crate::http::admin::AdminNodeDetail,
        crate::http::admin::NodeIdentityStatus,
        crate::http::admin::ObservedNetworkIdentity,
        crate::http::admin::AdminNetwork,
        crate::http::admin::AdminNetworkDetail,
        crate::http::admin::AdminNetworkNode,
        crate::http::admin::NetworkCreateRequest,
        crate::http::admin::NetworkUpdateRequest,
        crate::http::admin::NetworkResponse,
        crate::http::admin::AdminBlockHistoryItem,
        crate::http::admin::AdminBlockHistoryResponse,
        crate::http::admin::AdminPeerHistory,
        crate::http::admin::AdminPeerAggregate,
        crate::http::admin::AdminPeerCountryCount,
        crate::http::admin::AdminPeerLagSummary,
        crate::http::admin::HostDiagnostic,
        crate::http::admin::HostComponentDiagnostic,
        crate::http::admin::ProcessDiagnostic,
        crate::http::admin::RpcDiagnostic,
        crate::http::admin::SyncDiagnostic,
        crate::http::admin::ConsensusDiagnostic,
        crate::http::admin::ComponentDiagnostic,
        crate::http::admin::AdminOverview,
        crate::http::admin::AdminOverviewSummary,
        crate::http::admin::AgentSummary,
        crate::http::admin::NodeSummary,
        crate::http::admin::AttentionItem,
        crate::http::admin::AgentDiagnostic,
        crate::http::admin::AgentCredentialSummary,
        crate::http::admin::EnrollmentTokenResponse,
        crate::http::admin::TokenLifetimeRequest,
        crate::http::admin::RecoveryTokenResponse,
        crate::http::admin::RotationRequest,
        crate::http::admin::RotationResponse,
        crate::http::admin::RevokeResponse,
        crate::http::validators_admin::Validator,
        crate::http::validators_admin::ValidatorDetail,
        crate::http::validators_admin::NodeValidatorLink,
        crate::http::validators_admin::AdminValidatorHistoryLink,
        crate::http::validators_admin::AdminValidatorHistoryEntry,
        crate::http::validators_admin::AdminValidatorHistoryResponse,
        crate::http::validators_admin::ValidatorCreateRequest,
        crate::http::validators_admin::ValidatorLinkCreateRequest,
        crate::http::validators_admin::ValidatorLinkUpdateRequest,
        crate::http::validators_admin::ValidatorLinkEndRequest,
        crate::http::validators_admin::ValidatorMutationResponse,
        crate::http::validators_admin::ValidatorLinkMutationResponse,
        crate::http::admin::AgentAuditItem,
        crate::http::admin::AgentAuditResponse,
        crate::http::admin::GeoStatusDiagnostic,
        crate::http::access::Person,
        crate::http::access::PeopleResponse,
        crate::http::access::CreatePersonRequest,
        crate::http::access::PersonRoleRequest,
        crate::http::access::PersonStatusRequest,
        crate::http::access::ResetPasswordRequest,
        crate::http::access::SessionItem,
        crate::http::access::SessionsResponse,
        crate::http::access::RevokeSessionRequest,
        crate::http::access::RevokeSessionResponse,
        crate::http::access::RevokeOthersResponse,
        crate::http::access::AuditItem,
        crate::http::access::AuditResponse,
        crate::http::access::AccessSettingsResponse,
        crate::http::access::AccessSettingsRequest,
        crate::http::alerts_admin::AlertRuleSummary,
        crate::http::alerts_admin::RuleEvaluationSummary,
        crate::http::alerts_admin::AlertRuleDetail,
        crate::http::alerts_admin::RuleVersionDto,
        crate::http::alerts_admin::RuleOverrideDto,
        crate::http::alerts_admin::RuleStateDto,
        crate::http::alerts_admin::AlertRuleUpdateRequest,
        crate::http::alerts_admin::AlertRuleUpdateResponse,
        crate::http::alerts_admin::RuleOverrideUpsertRequest,
        crate::http::alerts_admin::RuleOverrideResponse,
        crate::http::alerts_admin::RulePreviewRequest,
        crate::http::alerts_admin::RulePreviewResponse,
        crate::http::alerts_admin::RulePreviewSubject,
        crate::http::alerts_admin::PreviewInput,
        crate::http::alerts_admin::IncidentListItem,
        crate::http::alerts_admin::IncidentListResponse,
        crate::http::alerts_admin::IncidentDetail,
        crate::http::alerts_admin::SilenceDto,
        crate::http::alerts_admin::SilenceListResponse,
        crate::http::alerts_admin::SilenceCreateRequest,
        crate::http::alerts_admin::SilenceMutationResponse,
        crate::http::alerts_admin::MaintenanceDto,
        crate::http::alerts_admin::MaintenanceListResponse,
        crate::http::alerts_admin::MaintenanceCreateRequest,
        crate::http::alerts_admin::MaintenanceMutationResponse,
        crate::notifications::DeliveryRow,
        crate::notifications::AttemptRow,
        crate::notifications::EventRow,
        crate::http::notifications_admin::DeliverySummary,
        crate::http::notifications_admin::NotificationEventItem,
        crate::http::notifications_admin::NotificationEventsResponse,
        crate::http::notifications_admin::NotificationEventDetail,
        crate::http::notifications_admin::NotificationDeliveriesResponse,
        crate::http::notifications_admin::NotificationDeliveryDetail,
        crate::http::notifications_admin::ChannelDto,
        crate::http::notifications_admin::DeliveryRetryResponse,
        crate::http::notifications_admin::ChannelTestResponse,
        crate::http::operations_admin::OperationSummary,
        crate::http::operations_admin::OperationDetail,
        crate::http::operations_admin::OperationIssue,
        crate::http::operations_admin::OperationMutationResponse,
        crate::http::operations_admin::RetentionPolicyDto,
        crate::http::operations_admin::RetentionOverview,
        crate::http::operations_admin::RetentionImpactRequest,
        crate::http::operations_admin::RetentionImpact,
        crate::http::operations_admin::RetentionBounds,
        crate::http::operations_admin::RetentionPolicyUpdateRequest,
        crate::http::operations_admin::RetentionPolicyMutationResponse,
        crate::http::operations_admin::RetentionRunRequest,
        crate::http::operations_admin::BackupArtifactSummary,
        crate::http::operations_admin::BackupArtifactDetail,
        crate::http::operations_admin::DoctorCheckDto,
        crate::http::operations_admin::DoctorOverview,
        crate::http::operations_admin::RestoreValidateRequest,
        crate::http::operations_admin::RestoreValidation,
        crate::http::operations_admin::RestoreSubmitRequest,
        crate::alerts::RuleCondition,
        crate::alerts::ParamSchema,
        crate::alerts::SubjectKind,
        crate::alerts::SuppressionMatch,
        crate::http::public::PublicAccessSettings,
        crate::http::agent::EnrollResponse,
        crate::http::agent::RecoverResponse,
    )),
    modifiers(&AgentBearerScheme),
    tags(
        (name = "system", description = "Operational health endpoints"),
        (name = "public", description = "Home Public Projection routes and DTOs"),
        (name = "admin", description = "Owner administration routes and DTOs"),
        (name = "agent", description = "Agent enrollment, recovery, and report ingestion; never generated into the browser client"),
    )
)]
pub struct ApiDoc;

/// Serialize the OpenAPI document as pretty JSON. Deterministic for the same
/// code, which lets CI regenerate `docs/openapi/openapi.json` and verify no
/// diff.
pub fn spec_json() -> String {
    ApiDoc::openapi()
        .to_pretty_json()
        .expect("OpenAPI document must serialize")
}
