#!/usr/bin/env python3
"""Issue #212 Story 46 baseline: capacity and performance for two Agents and six Nodes.

This script produces a *measured baseline*, not a production capacity promise.
Story 46 asks for a capacity and performance report with explicit sampling,
mount and hardware conditions, so every number in the output is tied to

  * the exact Server binary built from this checkout,
  * the filesystem the temporary state directory actually lives on,
  * the declared Agent cadence (a fast path plus a much slower scan), and
  * the observed low-space protection state machine on real database rows.

The Server is driven through its real surfaces: the production binary, the
real Owner login and Admin API, real Agent Enrollment over the Agent HTTP
surface, real Report ingestion into a temporary SQLite database, and real
capacity protection transitions produced by rewriting the deployment policy
and restarting the process. Reports are generated by a deterministic load
generator seeded from --seed; that substitution, the retention window and the
missing history family are listed under "not_delivered" instead of being
extrapolated into a guarantee.

Usage:
    python3 scripts/capacity-baseline.py --output-root target/capacity-baseline
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import http.client
import json
import os
import random
import signal
import socket
import sqlite3
import subprocess
import sys
import time
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIXTURE_DIR = ROOT / "crates/platpulse-core/tests/fixtures"
DEFAULT_BINARY = ROOT / "target/debug/platpulse-server"

AGENT_COUNT = 2
NODES_PER_AGENT = 3
SLOW_SCAN_EVERY = 4

HOST_METRICS = ("network_rx_bytes_per_sec", "network_tx_bytes_per_sec")
STEADY_NODE_METRICS = ("process_cpu_percent", "process_memory_percent")
SLOW_SCAN_NODE_METRICS = ("data_directory_percent", "peer_inbound_count", "peer_outbound_count")

NETWORK = {
    "networkKey": "platon-mainnet",
    "displayName": "PlatON Mainnet",
    "genesisHash": "0x" + "a" * 64,
    "chainId": 210425,
    "p2pNetworkId": 210425,
    "addressHrp": "lat",
}

OWNER_USERNAME = "admin"
OWNER_PASSWORD = "capacity-baseline-owner-2026"

# SQLite cannot round-trip u64::MAX, so the Server stores at most i64::MAX
# (CapacityConfig::MAX_PERSISTED_BYTES). Using that value as the pause floor
# makes the pause floor unreachable for any real mount, which is how the
# pressure phase forces protection on without touching the filesystem.
MAX_PERSISTED_BYTES = 2**63 - 1

# The capacity sampling cadence declared in the deployment policy. Five
# seconds is the smallest cadence the Server accepts, so the baseline samples
# the mount far more often than a production deployment would.
FAST_SAMPLE_SECONDS = 5

# Test thresholds for the steady phase. The Server invents no default
# threshold, so the baseline declares deliberately small ones that sit an
# order of magnitude below the mount's measured free space and therefore keep
# protection off while the write path is measured.
STEADY_PAUSE_BYTES = 1 * 1024 * 1024 * 1024
STEADY_RESUME_BYTES = 2 * 1024 * 1024 * 1024


class BaselineError(RuntimeError):
    """The baseline run cannot continue with trustworthy numbers."""


class Check:
    """A self-check on the numbers the report publishes."""

    def __init__(self, name: str, expected, observed) -> None:
        self.name = name
        self.expected = expected
        self.observed = observed

    @property
    def ok(self) -> bool:
        return self.expected == self.observed

    def as_json(self) -> dict:
        return {"name": self.name, "expected": self.expected, "observed": self.observed, "ok": self.ok}


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def advance_timestamp(previous: str | None) -> str:
    """Never reuse a second already used for a sample primary key."""
    now = datetime.now(timezone.utc)
    if previous is not None:
        last = datetime.strptime(previous, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
        if now <= last:
            now = last + timedelta(seconds=1)
    return now.strftime("%Y-%m-%dT%H:%M:%SZ")


def command(args, *, input_text: str | None = None, timeout: float = 900, cwd: Path = ROOT):
    completed = subprocess.run(
        [str(item) for item in args],
        input=input_text,
        capture_output=True,
        text=True,
        cwd=str(cwd),
        timeout=timeout,
        check=False,
    )
    if completed.returncode != 0:
        raise BaselineError(
            "command failed with status "
            + str(completed.returncode)
            + ": "
            + " ".join(str(item) for item in args)
            + "\n"
            + completed.stderr.strip()[:2000]
        )
    return completed


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.bind(("127.0.0.1", 0))
        return int(probe.getsockname()[1])


def json_bytes(value) -> bytes:
    return json.dumps(value, separators=(",", ":"), sort_keys=True).encode("utf-8")


def percentile(values: list[float], fraction: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = fraction * (len(ordered) - 1)
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    weight = position - lower
    return ordered[lower] * (1 - weight) + ordered[upper] * weight


def human_bytes(value: int | None) -> str:
    if value is None:
        return "unknown"
    size = float(value)
    for unit in ("B", "KiB", "MiB", "GiB", "TiB"):
        if size < 1024 or unit == "TiB":
            return f"{size:.2f} {unit}"
        size /= 1024
    return f"{size:.2f} TiB"


def filesystem_sample(path: Path) -> dict:
    stat = os.statvfs(str(path))
    unit = stat.f_frsize or stat.f_bsize
    return {
        "path": str(path),
        "fragment_size": unit,
        "total_bytes": unit * stat.f_blocks,
        "available_bytes": unit * stat.f_bavail,
        "free_bytes": unit * stat.f_bfree,
    }


def mount_conditions(path: Path) -> dict:
    resolved = str(path.resolve())
    best: tuple[str, str, str] | None = None
    for line in Path("/proc/mounts").read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        point, filesystem_type = parts[1], parts[2]
        if resolved == point or resolved.startswith(point.rstrip("/") + "/"):
            if best is None or len(point) > len(best[0]):
                best = (point, filesystem_type, parts[0])
    if best is None:
        return {"mount_point": None, "filesystem_type": None, "mount_source": None}
    return {"mount_point": best[0], "filesystem_type": best[1], "mount_source": best[2]}


def hardware_conditions() -> dict:
    uname = os.uname()
    cpu_model = None
    cpuinfo = Path("/proc/cpuinfo")
    if cpuinfo.is_file():
        for line in cpuinfo.read_text(encoding="utf-8").splitlines():
            if line.lower().startswith("model name"):
                cpu_model = line.split(":", 1)[1].strip()
                break
    memory_total = None
    meminfo = Path("/proc/meminfo")
    if meminfo.is_file():
        for line in meminfo.read_text(encoding="utf-8").splitlines():
            if line.startswith("MemTotal:"):
                memory_total = int(line.split()[1]) * 1024
                break
    return {
        "kernel": uname.sysname + " " + uname.release,
        "machine": uname.machine,
        "cpu_model": cpu_model,
        "cpu_cores": os.cpu_count(),
        "memory_total_bytes": memory_total,
        "python_version": sys.version.split()[0],
    }


# Development mode deliberately shares the Server database with local
# tooling, but an external SQLite connection interleaved with live Server
# writes corrupts the shared WAL index: while building this baseline a CLI
# write plus a python read raced the Server's own enrollment transaction and
# the database ended up with "wrong number of entries in index
# sqlite_autoindex_enrollment_tokens_2". Every database read here therefore
# happens in a stopped-Server window, and this flag enforces that invariant
# instead of relying on call ordering.
SERVER_RUNNING = False


def file_bytes(path: Path) -> int:
    try:
        return path.stat().st_size
    except FileNotFoundError:
        return 0


def sqlite_connection(db_path: Path):
    """Read the temporary database, only while the Server is stopped."""
    if SERVER_RUNNING:
        raise BaselineError(
            "refusing to read " + str(db_path) + " while the Server is running: an external SQLite "
            "connection next to live Server writes corrupts the shared WAL index, so every "
            "measurement must use a stopped-Server window"
        )
    try:
        connection = sqlite3.connect("file:" + str(db_path) + "?mode=ro", uri=True)
        connection.execute("SELECT 1 FROM _sqlx_migrations LIMIT 1").fetchone()
        return connection
    except sqlite3.Error:
        return sqlite3.connect(str(db_path))


def sqlite_rows(db_path: Path, sql: str) -> list[dict]:
    connection = sqlite_connection(db_path)
    try:
        connection.row_factory = sqlite3.Row
        return [dict(row) for row in connection.execute(sql).fetchall()]
    finally:
        connection.close()


def sqlite_scalar(db_path: Path, sql: str) -> int:
    rows = sqlite_rows(db_path, sql)
    if not rows:
        return 0
    return int(list(rows[0].values())[0])


def write_config(
    path: Path,
    *,
    state_dir: Path,
    db_path: Path,
    pepper_path: Path,
    web_root: Path,
    port: int,
    metrics_port: int,
    capacity_enabled: bool,
    pause_bytes: int | None,
    resume_bytes: int | None,
    sample_seconds: int,
) -> None:
    lines = [
        "# Generated by scripts/capacity-baseline.py for issue #212 Story 46.",
        'state_dir = "' + str(state_dir) + '"',
        'db_path = "' + str(db_path) + '"',
        'pepper_file = "' + str(pepper_path) + '"',
        # /health/ready waits for web assets, so the baseline serves the real
        # production WebUI build instead of reporting a not-ready Server.
        'web_root = "' + str(web_root) + '"',
        'listen = "127.0.0.1:' + str(port) + '"',
        'public_base_url = "http://127.0.0.1:' + str(port) + '"',
        "development = true",
        "",
        "[capacity]",
        "enabled = " + ("true" if capacity_enabled else "false"),
    ]
    if pause_bytes is not None:
        lines.append("pause_below_bytes = " + str(pause_bytes))
    if resume_bytes is not None:
        lines.append("resume_above_bytes = " + str(resume_bytes))
    lines.append("sample_interval_seconds = " + str(sample_seconds))
    lines += [
        "",
        # The Prometheus surface lives on its own internal listener; the main
        # listener routes /metrics to not-found by design. A loopback address in
        # development needs no trusted proxy, so the baseline can scrape it.
        "[metrics]",
        "enabled = true",
        'listen = "127.0.0.1:' + str(metrics_port) + '"',
    ]
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


class Client:
    """Minimal HTTP client shaped like scripts/release-qualification.py."""

    def __init__(self, port: int, timeout: float) -> None:
        self.port = port
        self.timeout = timeout

    def request(self, method: str, path: str, *, body: bytes | None = None, headers: dict | None = None):
        started = time.monotonic()
        connection = http.client.HTTPConnection("127.0.0.1", self.port, timeout=self.timeout)
        try:
            connection.request(method, path, body=body, headers=headers or {})
            response = connection.getresponse()
            payload = response.read()
            elapsed = (time.monotonic() - started) * 1000
            return response.status, {key.lower(): value for key, value in response.getheaders()}, payload, elapsed
        finally:
            connection.close()


class ServerProcess:
    """The packaged Server under test, started with its deployment config."""

    def __init__(self, binary: Path, config: Path, log_path: Path, port: int, timeout: float) -> None:
        self.binary = binary
        self.config = config
        self.log_path = log_path
        self.port = port
        self.timeout = timeout
        self.process: subprocess.Popen | None = None
        self.log_handle = None

    def start(self) -> None:
        global SERVER_RUNNING
        self.log_handle = self.log_path.open("a", encoding="utf-8")
        self.log_handle.write("\n=== baseline start " + utc_now() + " ===\n")
        self.log_handle.flush()
        self.process = subprocess.Popen(
            [str(self.binary), "serve", "--config", str(self.config)],
            cwd=str(ROOT),
            stdout=self.log_handle,
            stderr=subprocess.STDOUT,
            text=True,
        )
        client = Client(self.port, self.timeout)
        live = False
        for _ in range(200):
            if self.process.poll() is not None:
                raise BaselineError("Server exited during startup; see " + str(self.log_path))
            try:
                status, _, _, _ = client.request("GET", "/health/live")
                if status == 200:
                    live = True
                    break
            except OSError:
                pass
            time.sleep(0.1)
        if not live:
            raise BaselineError("Server did not become live")
        for _ in range(200):
            try:
                status, _, _, _ = client.request("GET", "/health/ready")
                if status == 200:
                    SERVER_RUNNING = True
                    return
            except OSError:
                pass
            time.sleep(0.1)
        raise BaselineError("Server did not become ready")

    def stop(self) -> None:
        global SERVER_RUNNING
        SERVER_RUNNING = False
        if self.process is None:
            return
        if self.process.poll() is None:
            self.process.send_signal(signal.SIGTERM)
            try:
                self.process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=5)
        if self.log_handle is not None:
            self.log_handle.close()
        self.process = None
        self.log_handle = None


def login(client: Client, username: str, password: str) -> tuple[str, str]:
    status, headers, body, _ = client.request(
        "POST",
        "/api/public/v1/login",
        body=json_bytes({"username": username, "password": password}),
        headers={"Content-Type": "application/json", "Origin": "http://127.0.0.1:" + str(client.port)},
    )
    if status != 200:
        raise BaselineError("Owner login failed with status " + str(status))
    cookie = headers.get("set-cookie", "").split(";", 1)[0]
    return cookie, str(json.loads(body).get("csrfToken", ""))


def admin_get(client: Client, cookie: str, path: str):
    return client.request("GET", path, headers={"Cookie": cookie})


def admin_post(client: Client, cookie: str, csrf: str, path: str, payload: dict):
    return client.request(
        "POST",
        path,
        body=json_bytes(payload),
        headers={
            "Cookie": cookie,
            "Content-Type": "application/json",
            "Origin": "http://127.0.0.1:" + str(client.port),
            "x-csrf-token": csrf,
        },
    )


def create_enrollment_token(binary: Path, config: Path) -> str:
    output = command([binary, "agent", "create-enrollment-token", "--config", config])
    tokens = [line.strip() for line in output.stdout.splitlines() if line.strip().startswith("pp_enroll_")]
    if not tokens:
        raise BaselineError("create-enrollment-token returned no token")
    return tokens[-1]


def enroll_agent(token: str, client: Client, agent_index: int) -> dict:
    """Real Agent Enrollment over the Agent HTTP surface.

    Enrollment carries no request body, so it uses curl exactly like
    scripts/release-qualification.py does.
    """
    url = "http://127.0.0.1:" + str(client.port) + "/api/agent/v1/enroll"
    completed = subprocess.run(
        [
            "curl",
            "-sS",
            "--connect-timeout",
            "2",
            "--max-time",
            str(client.timeout),
            "-H",
            "Authorization: Bearer " + token,
            "-X",
            "POST",
            url,
            "-w",
            "\n%{http_code}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise BaselineError("Agent Enrollment transport failed: " + completed.stderr.strip()[:400])
    body, status_text = completed.stdout.rsplit("\n", 1)
    if int(status_text) != 200:
        raise BaselineError("Agent Enrollment failed with status " + status_text + ": " + body.strip()[:400])
    payload = json.loads(body)
    return {
        "agent_index": agent_index,
        "agent_id": payload["agent_id"],
        "agent_epoch": int(payload["agent_epoch"]),
        "credential": payload["credential"],
        "boot_id": str(uuid.uuid4()),
    }


def agent_diagnostics(client: Client, cookie: str) -> list:
    """Agents the running Server itself reports, read over HTTP.

    This is how the baseline confirms Server-side state while the Server
    runs: it must not attach an external SQLite connection.
    """
    status, _, payload, _ = admin_get(client, cookie, "/api/admin/v1/agents")
    if status != 200:
        raise BaselineError("GET /api/admin/v1/agents failed with status " + str(status))
    body = json.loads(payload)
    return body if isinstance(body, list) else body.get("agents", [])


def send_report(client: Client, credential: str, body: bytes):
    status, _, payload, elapsed = client.request(
        "POST",
        "/api/agent/v1/reports",
        body=body,
        headers={"Authorization": "Bearer " + credential, "Content-Type": "application/json"},
    )
    return status, payload, elapsed


def recursive_replace(value, replacements: dict):
    if isinstance(value, dict):
        return {key: recursive_replace(item, replacements) for key, item in value.items()}
    if isinstance(value, list):
        return [recursive_replace(item, replacements) for item in value]
    if isinstance(value, str):
        return replacements.get(value, value)
    return value


def bump_observation_revisions(value, increment: int, observed_at: str) -> None:
    """Age every observation in the payload so each Report is a fresh one."""
    if isinstance(value, dict):
        for key in ("state_revision", "value_revision"):
            if isinstance(value.get(key), int):
                value[key] = value[key] + increment
        for key in ("attempted_at", "latest_observed_at", "observed_at"):
            if isinstance(value.get(key), str):
                value[key] = observed_at
        for item in value.values():
            bump_observation_revisions(item, increment, observed_at)
    elif isinstance(value, list):
        for item in value:
            bump_observation_revisions(item, increment, observed_at)


def observation(latest, observed_at: str) -> dict:
    return {
        "status": "ok",
        "attempted_at": observed_at,
        "latest_observed_at": observed_at,
        "state_revision": 1,
        "value_revision": 1,
        "latest": latest,
    }


def peer_component(observed_at: str, inbound: int, outbound: int, sequence: int) -> dict:
    peers = []
    for index in range(inbound + outbound):
        direction = "inbound" if index < inbound else "outbound"
        peers.append(
            {
                "peer_id": "baseline-peer-" + direction + "-" + str(index + 1),
                "remote_ip": "203.0.113." + str(10 + index),
                "direction": direction,
                "trusted": index % 2 == 0,
                "static_peer": False,
                "consensus_peer": True,
                "client_name": "PlatON/v1.4.0",
                "caps": ["cbft/1", "platon/1"],
                "cbft_protocol_version": 1,
                "cbft_highest_qc_block": 100000 + sequence * 10 + index,
                "cbft_locked_block": 99999 + sequence * 10 + index,
                "cbft_commit_block": 99998 + sequence * 10 + index,
            }
        )
    return observation({"peers": peers}, observed_at)


def baseline_block_hash(node_id: str, height: int) -> str:
    """A deterministic 32-byte block hash for a declared (Node, height)."""
    seed = node_id + ":" + str(height)
    return "0x" + hashlib.sha256(seed.encode("utf-8")).hexdigest()


def baseline_node_ids() -> list[list[str]]:
    return [
        [str(uuid.uuid5(uuid.NAMESPACE_URL, "platpulse-baseline-node-" + str(agent) + "-" + str(node))) for node in range(NODES_PER_AGENT)]
        for agent in range(AGENT_COUNT)
    ]


def build_report(
    template: dict,
    minimal: dict,
    *,
    identity: dict,
    sequence: int,
    observed_at: str,
    node_ids: list[str],
    agent_index: int,
    head_base: int,
    slow_scan: bool,
    rng: random.Random,
) -> dict:
    report = copy.deepcopy(template)
    report["agent_id"] = identity["agent_id"]
    report["agent_epoch"] = identity["agent_epoch"]
    report["boot_id"] = identity["boot_id"]
    report["report_id"] = str(uuid.uuid4())
    report["report_sequence"] = sequence
    report["generated_at"] = observed_at

    # The canonical fixture carries host components in error states, so the
    # baseline host payload starts from the fixture whose host is fully ok:
    # that is what makes the generic writer persist host network history.
    report["host"] = copy.deepcopy(minimal["host"])
    report["host"]["cpu_percent"] = observation(round(rng.uniform(4.0, 55.0), 2), observed_at)
    report["host"]["memory"] = observation(
        {"total_bytes": 17179869184, "used_bytes": int(4.5e9 + rng.uniform(0.0, 2.0e9))}, observed_at
    )
    report["host"]["network_throughput"] = observation(
        {
            "rx_bytes_per_sec": int(rng.uniform(20000.0, 900000.0)),
            "tx_bytes_per_sec": int(rng.uniform(10000.0, 400000.0)),
        },
        observed_at,
    )

    base_nodes = template["nodes"]
    nodes = []
    inventory = []
    for index, node_id in enumerate(node_ids):
        source = base_nodes[index % len(base_nodes)]
        node = recursive_replace(copy.deepcopy(source), {source["node_id"]: node_id})
        # Every baseline Node runs a live Validator process, so all six Nodes
        # contribute the same optional Node series every round.
        node["process"] = copy.deepcopy(base_nodes[0]["process"])
        sync = node.get("chain", {}).get("sync", {}).get("latest")
        if isinstance(sync, dict):
            sync["current_block"] = head_base + index
            sync["highest_block"] = max(int(sync.get("highest_block", 0)), head_base + index)
        if slow_scan:
            node["data_directory_size_bytes"] = observation(int(6.5e11 + rng.uniform(0.0, 5.0e8)), observed_at)
            node["data_directory_capacity_bytes"] = observation(1099511627776, observed_at)
            node["chain"]["peers"] = peer_component(observed_at, 2, 2, sequence)
        else:
            node.pop("data_directory_size_bytes", None)
            node.pop("data_directory_capacity_bytes", None)
            node["chain"].pop("peers", None)
        nodes.append(node)
        inventory.append(
            {
                "node_id": node_id,
                "display_name": "Baseline Node " + str(agent_index + 1) + "-" + str(index + 1),
                "network_key": NETWORK["networkKey"],
                "rpc_endpoint": "ws://127.0.0.1:" + str(6790 + agent_index * 10 + index),
            }
        )

    # The canonical fixture declares two Nodes, so its Block Summaries and
    # History Gaps reference Node IDs this Report replaces. Remap them with the
    # same index-modulo rule used to build the Node set (the rule
    # scripts/release-qualification.py already proves), because the Server
    # rejects a Report whose entries reference an undeclared Node.
    fixture_nodes = [item["node_id"] for item in template["inventory"]["nodes"]]
    node_mapping = {old: node_ids[index % len(node_ids)] for index, old in enumerate(fixture_nodes)}
    # A live Node advances its chain every round, so the baseline shifts the
    # fixture heights with the round instead of replaying fixed ones: a sample
    # at or below the retained high-water mark answers "resync_replay" and the
    # receipt would read partially_accepted for a reason this measurement is
    # not about. Hashes follow the shifted height so no height is ever claimed
    # with two different hashes.
    blocks = recursive_replace(copy.deepcopy(template["block_summaries"]), node_mapping)
    first_height = head_base - len(blocks)
    observed_ms = int(datetime.fromisoformat(observed_at.replace("Z", "+00:00")).timestamp() * 1000)
    for offset, block in enumerate(blocks):
        height = first_height + offset
        block["block_number"] = height
        block["block_hash"] = baseline_block_hash(block["node_id"], height)
        block["parent_hash"] = baseline_block_hash(block["node_id"], height - 1)
        block["block_timestamp_ms"] = observed_ms - (len(blocks) - offset) * 2000
        block["observed_at"] = observed_at
        if block.get("source") == "gap_backfill":
            block["source"] = "subscription"
        block.pop("block_interval_ms", None)
    report["block_summaries"] = blocks
    report["history_gaps"] = recursive_replace(report["history_gaps"], node_mapping)

    report["nodes"] = nodes
    report["inventory"] = {"revision": sequence, "nodes": inventory}
    bump_observation_revisions(report, sequence - 1, observed_at)
    return report


CORE_TABLES = (
    "agent_report_receipts",
    "current_host_observations",
    "current_node_process_observations",
    "current_node_chain_observations",
    "agents",
    "nodes",
)


def core_counts(db_path: Path) -> dict:
    return {table: sqlite_scalar(db_path, "SELECT COUNT(*) FROM " + table) for table in CORE_TABLES}


def optional_counts(db_path: Path) -> dict:
    return {
        "host_samples": sqlite_scalar(db_path, "SELECT COUNT(*) FROM host_metric_samples"),
        "node_samples": sqlite_scalar(db_path, "SELECT COUNT(*) FROM node_metric_samples"),
        "host_series": sqlite_scalar(
            db_path, "SELECT COUNT(*) FROM (SELECT DISTINCT agent_id, metric FROM host_metric_samples)"
        ),
        "node_series": sqlite_scalar(
            db_path, "SELECT COUNT(*) FROM (SELECT DISTINCT node_id, metric FROM node_metric_samples)"
        ),
        "host_by_metric": sqlite_rows(
            db_path,
            "SELECT metric, COUNT(*) AS samples, COUNT(DISTINCT agent_id) AS scopes "
            "FROM host_metric_samples GROUP BY metric ORDER BY metric",
        ),
        "node_by_metric": sqlite_rows(
            db_path,
            "SELECT metric, COUNT(*) AS samples, COUNT(DISTINCT node_id) AS scopes "
            "FROM node_metric_samples GROUP BY metric ORDER BY metric",
        ),
        "node_rows_per_series": sqlite_rows(
            db_path,
            "SELECT COUNT(*) AS series, MIN(samples) AS least, MAX(samples) AS most, "
            "AVG(samples) AS mean FROM (SELECT COUNT(*) AS samples FROM node_metric_samples GROUP BY node_id, metric)",
        ),
        "host_rows_per_series": sqlite_rows(
            db_path,
            "SELECT COUNT(*) AS series, MIN(samples) AS least, MAX(samples) AS most, "
            "AVG(samples) AS mean FROM (SELECT COUNT(*) AS samples FROM host_metric_samples GROUP BY agent_id, metric)",
        ),
    }


def storage_bytes(db_path: Path) -> dict:
    return {
        "database_bytes": file_bytes(db_path),
        "wal_bytes": file_bytes(db_path.with_name(db_path.name + "-wal")),
        "shm_bytes": file_bytes(db_path.with_name(db_path.name + "-shm")),
    }


def larger_storage(left: dict, right: dict) -> dict:
    "Element-wise maximum: the largest live reading of a file that also shrinks."
    return {key: max(left[key], right[key]) for key in left}


def capacity_state(client: Client, cookie: str) -> dict:
    status, _, payload, elapsed = admin_get(client, cookie, "/api/admin/v1/capacity")
    if status != 200:
        raise BaselineError("GET /api/admin/v1/capacity failed with status " + str(status))
    body = json.loads(payload)
    intervals = body.get("recentIntervals") or []
    return {
        "elapsed_ms": round(elapsed, 2),
        "enabled": body["enabled"],
        "protected": body["protected"],
        "pause_below_bytes": body["pauseBelowBytes"],
        "resume_above_bytes": body["resumeAboveBytes"],
        "sample_interval_seconds": body["sampleIntervalSeconds"],
        "policy_origin": body["policyOrigin"],
        "mount_path": body["mountPath"],
        "sampled_at": body["sampledAt"],
        "available_bytes": (body.get("sample") or {}).get("availableBytes"),
        "total_bytes": (body.get("sample") or {}).get("totalBytes"),
        "active_interval_id": body["activeIntervalId"],
        "sampling_error": body["samplingError"],
        "transition_error": body["transitionError"],
        "recent_intervals": intervals[:3],
    }


def measure_reads(client: Client, cookie: str, samples: int, metrics_client: Client) -> dict:
    measured = {}
    for name, path, use_metrics in (
        ("capacity", "/api/admin/v1/capacity", False),
        ("operations", "/api/admin/v1/operations?limit=50", False),
        ("metrics", "/metrics", True),
    ):
        latencies = []
        status_seen = None
        for _ in range(samples):
            if use_metrics:
                status, _, _, elapsed = metrics_client.request("GET", path)
            else:
                status, _, _, elapsed = admin_get(client, cookie, path)
            status_seen = status
            if status != 200:
                break
            latencies.append(elapsed)
        if not latencies:
            measured[name] = {"path": path, "samples": 0, "status": status_seen, "error": "not measured"}
            continue
        measured[name] = {
            "path": path,
            "status": status_seen,
            "samples": len(latencies),
            "p50_ms": round(percentile(latencies, 0.5), 2),
            "p95_ms": round(percentile(latencies, 0.95), 2),
            "min_ms": round(min(latencies), 2),
            "max_ms": round(max(latencies), 2),
        }
    return measured


def capacity_gauges(client: Client) -> list[str]:
    status, _, payload, _ = client.request("GET", "/metrics")
    if status != 200:
        return ["metrics endpoint returned status " + str(status)]
    text = payload.decode("utf-8", errors="replace")
    return [line for line in text.splitlines() if line.startswith("platpulse_capacity_")]


def skipped_series_rows(db_path: Path) -> list[dict]:
    return sqlite_rows(
        db_path,
        "SELECT scope_kind, scope_key, metric, skipped_count, first_skipped_at, last_skipped_at "
        "FROM capacity_skipped_series ORDER BY scope_kind, metric, scope_key",
    )


def interval_rows(db_path: Path) -> list[dict]:
    return sqlite_rows(
        db_path,
        "SELECT interval_id, source_mount, started_at, started_reason, opened_total_bytes, "
        "opened_available_bytes, pause_below_bytes, resume_above_bytes, ended_at, ended_reason, "
        "resumed_total_bytes, resumed_available_bytes FROM capacity_protection_intervals ORDER BY started_at",
    )


class BaselineRun:
    def __init__(self, args) -> None:
        self.args = args
        self.rng = random.Random(args.seed)
        self.run_root = args.output_root.resolve() / time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
        self.state_dir = self.run_root / "state"
        self.db_path = self.state_dir / "platpulse.db"
        self.pepper_path = self.state_dir / "server-pepper"
        self.config_path = self.run_root / "server.toml"
        self.log_path = self.run_root / "server.log"
        self.port = free_port()
        self.metrics_port = free_port()
        while self.metrics_port == self.port:
            self.metrics_port = free_port()
        self.binary = args.binary.resolve()
        self.web_root = args.web_root.resolve()
        self.client = Client(self.port, 30.0)
        self.metrics_client = Client(self.metrics_port, 30.0)
        self.server: ServerProcess | None = None
        self.cookie = ""
        self.csrf = ""
        self.agents: list[dict] = []
        self.node_ids = baseline_node_ids()
        self.sequences = [0, 0]
        self.observed_at: str | None = None
        self.checks: list[Check] = []
        self.report: dict = {}
        self.runtime_seconds = 0.0
        self.template: dict = {}
        self.minimal: dict = {}

    def write_policy(self, *, enabled: bool, pause: int | None, resume: int | None) -> None:
        write_config(
            self.config_path,
            state_dir=self.state_dir,
            db_path=self.db_path,
            pepper_path=self.pepper_path,
            web_root=self.web_root,
            port=self.port,
            metrics_port=self.metrics_port,
            capacity_enabled=enabled,
            pause_bytes=pause,
            resume_bytes=resume,
            sample_seconds=FAST_SAMPLE_SECONDS,
        )

    def start(self) -> None:
        self.server = ServerProcess(self.binary, self.config_path, self.log_path, self.port, 30.0)
        self.server.start()

    def stop(self) -> None:
        if self.server is not None:
            self.server.stop()
            self.server = None

    def next_timestamp(self) -> str:
        self.observed_at = advance_timestamp(self.observed_at)
        return self.observed_at

    def submit_round(self, *, slow_scan: bool, label: str) -> dict:
        observed_at = self.next_timestamp()
        head_base = 1_000_000 + self.sequences[0] * 5
        outcomes = []
        for index, agent in enumerate(self.agents):
            self.sequences[index] += 1
            report = build_report(
                self.template,
                self.minimal,
                identity=agent,
                sequence=self.sequences[index],
                observed_at=observed_at,
                node_ids=self.node_ids[index],
                agent_index=index,
                head_base=head_base,
                slow_scan=slow_scan,
                rng=self.rng,
            )
            status, payload, elapsed = send_report(self.client, agent["credential"], json_bytes(report))
            body = json.loads(payload) if payload else {}
            receipt = body.get("receipt") if isinstance(body.get("receipt"), dict) else {}
            outcomes.append(
                {
                    "agent_index": index,
                    "agent_id": agent["agent_id"],
                    "status": status,
                    "disposition": receipt.get("disposition"),
                    "receipt_id": receipt.get("report_id"),
                    "response": payload.decode("utf-8", errors="replace")[:400],
                    "elapsed_ms": round(elapsed, 2),
                }
            )
        rejected = [item for item in outcomes if item["status"] != 200]
        if rejected:
            raise BaselineError(label + " report submission failed: " + json.dumps(rejected))
        return {"label": label, "observed_at": observed_at, "slow_scan": slow_scan, "outcomes": outcomes}

    def steady_phase(self, baseline: dict) -> dict:
        "Measure the write path, then read the database with the Server stopped."
        # baseline carries the stopped-Server measurement taken just before the
        # first round, so this phase attaches an external SQLite connection
        # exactly once: after it has asked the Server to stop.
        rounds = self.args.rounds
        slow_rounds = [index for index in range(1, rounds + 1) if index % SLOW_SCAN_EVERY == 0]
        storage_before = baseline["storage"]
        started = time.monotonic()
        submissions: list[dict] = []
        # The WAL only exists while the Server runs: SQLite checkpoints and removes
        # it when the last connection closes, so a reading taken after the stop is
        # not the WAL this load produced. Sample the live files as the load runs.
        storage_peak = storage_bytes(self.db_path)
        for index in range(1, rounds + 1):
            submissions.append(self.submit_round(slow_scan=index in slow_rounds, label="steady round " + str(index)))
            storage_peak = larger_storage(storage_peak, storage_bytes(self.db_path))
            if index < rounds:
                time.sleep(self.args.interval)
        duration = time.monotonic() - started
        latencies = [item["elapsed_ms"] for submission in submissions for item in submission["outcomes"]]
        expected_samples = 0
        for index in range(1, rounds + 1):
            per_round = AGENT_COUNT * (len(HOST_METRICS) + NODES_PER_AGENT * len(STEADY_NODE_METRICS))
            if index in slow_rounds:
                per_round += AGENT_COUNT * NODES_PER_AGENT * len(SLOW_SCAN_NODE_METRICS)
            expected_samples += per_round
        capacity = capacity_state(self.client, self.cookie)
        reads = measure_reads(self.client, self.cookie, self.args.query_samples, self.metrics_client)
        # Read the loaded database and its WAL before stopping: this is the only
        # honest "after load" number. Stopping the Server and opening the database
        # with an external SQLite connection checkpoints the WAL away, which is how
        # an earlier revision of this script reported 0 bytes for a WAL that had
        # grown to megabytes.
        storage_after = storage_bytes(self.db_path)
        self.stop()
        storage_after_shutdown = storage_bytes(self.db_path)
        counts = optional_counts(self.db_path)
        core = core_counts(self.db_path)
        observed_samples = (
            counts["host_samples"]
            + counts["node_samples"]
            - baseline["optional"]["host_samples"]
            - baseline["optional"]["node_samples"]
        )
        host_samples = counts["host_samples"] - baseline["optional"]["host_samples"]
        receipts_added = core["agent_report_receipts"] - baseline["core"]["agent_report_receipts"]
        self.checks.append(Check("steady optional samples", expected_samples, observed_samples))
        self.checks.append(Check("steady host submissions", rounds * AGENT_COUNT, len(latencies)))
        self.checks.append(
            Check("steady host optional samples", rounds * AGENT_COUNT * len(HOST_METRICS), host_samples)
        )
        self.checks.append(Check("steady core receipts added", rounds * AGENT_COUNT, receipts_added))
        return {
            "rounds": rounds,
            "interval_seconds": self.args.interval,
            "slow_scan_every": SLOW_SCAN_EVERY,
            "slow_scan_rounds": slow_rounds,
            "duration_seconds": round(duration, 2),
            "submissions": len(latencies),
            "expected_optional_samples": expected_samples,
            "observed_optional_samples": observed_samples,
            "write_latency_ms": {
                "p50_ms": round(percentile(latencies, 0.5), 2),
                "p95_ms": round(percentile(latencies, 0.95), 2),
                "min_ms": round(min(latencies), 2),
                "max_ms": round(max(latencies), 2),
            },
            "throughput_submissions_per_second": round(len(latencies) / duration, 3) if duration > 0 else None,
            "host_optional_samples": host_samples,
            "receipts_added": receipts_added,
            "baseline_core_counts": baseline["core"],
            "baseline_optional_counts": baseline["optional"],
            "storage_before": storage_before,
            "storage_after": storage_after,
            "storage_peak": storage_peak,
            "storage_after_shutdown": storage_after_shutdown,
            "optional_counts": counts,
            "core_counts": core,
            "capacity": capacity,
            "read_path": reads,
        }

    def pressure_phase(self, steady_available_bytes: int) -> dict:
        self.stop()
        self.write_policy(enabled=True, pause=MAX_PERSISTED_BYTES, resume=MAX_PERSISTED_BYTES)
        core_before = core_counts(self.db_path)
        optional_before = optional_counts(self.db_path)
        self.start()
        observed = capacity_state(self.client, self.cookie)
        if not observed["protected"]:
            raise BaselineError("protection did not open under a pause floor above the mount")
        rounds = self.args.pressure_rounds
        submissions = []
        for index in range(1, rounds + 1):
            submissions.append(self.submit_round(slow_scan=False, label="pressure round " + str(index)))
            if index < rounds:
                time.sleep(1.0)
        capacity_after = capacity_state(self.client, self.cookie)
        gauges = capacity_gauges(self.metrics_client)
        self.stop()
        core_after = core_counts(self.db_path)
        optional_after = optional_counts(self.db_path)
        series_rows = skipped_series_rows(self.db_path)
        skipped_samples = sum(int(row["skipped_count"]) for row in series_rows)
        intervals = interval_rows(self.db_path)
        expected_samples = rounds * AGENT_COUNT * (len(HOST_METRICS) + NODES_PER_AGENT * len(STEADY_NODE_METRICS))
        self.checks.append(Check("pressure skipped samples", expected_samples, skipped_samples))
        self.checks.append(
            Check(
                "pressure optional samples unchanged",
                optional_before["host_samples"] + optional_before["node_samples"],
                optional_after["host_samples"] + optional_after["node_samples"],
            )
        )
        self.checks.append(
            Check(
                "pressure core receipts added",
                rounds * AGENT_COUNT,
                core_after["agent_report_receipts"] - core_before["agent_report_receipts"],
            )
        )
        return {
            "rounds": rounds,
            "mount_available_bytes": steady_available_bytes,
            "pause_below_bytes": MAX_PERSISTED_BYTES,
            "capacity_before": observed,
            "capacity_after": capacity_after,
            "capacity_gauges": gauges,
            "core_counts_before": core_before,
            "core_counts_after": core_after,
            "optional_counts_before": optional_before,
            "optional_counts_after": optional_after,
            "skipped_samples": skipped_samples,
            "skipped_series": series_rows,
            "intervals": intervals,
            "submissions": submissions,
            "submission_latency_ms": {
                "p50_ms": round(percentile([item["elapsed_ms"] for s in submissions for item in s["outcomes"]], 0.5), 2),
                "p95_ms": round(percentile([item["elapsed_ms"] for s in submissions for item in s["outcomes"]], 0.95), 2),
            },
        }

    def recovery_phase(self) -> dict:
        self.stop()
        released_sample = filesystem_sample(self.state_dir)
        release_floor = max(1, released_sample["available_bytes"] // 2)
        self.write_policy(enabled=True, pause=release_floor, resume=release_floor)
        optional_before = optional_counts(self.db_path)
        core_before = core_counts(self.db_path)
        self.start()
        observed = capacity_state(self.client, self.cookie)
        if observed["protected"]:
            raise BaselineError("protection stayed open after the pause floor moved below the free space")
        rounds = self.args.recovery_rounds
        submissions = []
        for index in range(1, rounds + 1):
            submissions.append(self.submit_round(slow_scan=False, label="recovery round " + str(index)))
            if index < rounds:
                time.sleep(1.0)
        capacity_after = capacity_state(self.client, self.cookie)
        gauges = capacity_gauges(self.metrics_client)
        self.stop()
        optional_after = optional_counts(self.db_path)
        core_after = core_counts(self.db_path)
        intervals = interval_rows(self.db_path)
        expected_samples = rounds * AGENT_COUNT * (len(HOST_METRICS) + NODES_PER_AGENT * len(STEADY_NODE_METRICS))
        observed_samples = (optional_after["host_samples"] - optional_before["host_samples"]) + (
            optional_after["node_samples"] - optional_before["node_samples"]
        )
        self.checks.append(Check("recovery optional samples resumed", expected_samples, observed_samples))
        closed = [row for row in intervals if row["ended_at"] is not None]
        self.checks.append(Check("protection interval closed once", 1, len(closed)))
        if closed:
            self.checks.append(Check("closure reason", "resumed", closed[-1]["ended_reason"]))
        return {
            "rounds": rounds,
            "release_floor_bytes": release_floor,
            "mount_available_bytes": released_sample["available_bytes"],
            "capacity_after": capacity_after,
            "capacity_gauges": gauges,
            "core_counts_before": core_before,
            "core_counts_after": core_after,
            "optional_counts_before": optional_before,
            "optional_counts_after": optional_after,
            "intervals": intervals,
            "skipped_series": skipped_series_rows(self.db_path),
            "submissions": submissions,
        }

    def run(self) -> dict:
        started_wall = time.monotonic()
        self.run_root.mkdir(parents=True, exist_ok=True)
        self.state_dir.mkdir(parents=True, exist_ok=True)
        if not self.binary.is_file():
            raise BaselineError("Server binary not found at " + str(self.binary))

        if not self.args.skip_build:
            command(["cargo", "build", "-p", "platpulse-server"], cwd=ROOT, timeout=1800)
        if not (self.web_root / "index.html").is_file():
            raise BaselineError(
                "the WebUI build is missing at "
                + str(self.web_root)
                + "; run npm run build in platpulse-web, because /health/ready waits for web assets"
            )

        self.template = json.loads((FIXTURE_DIR / "report_v1_canonical.json").read_text(encoding="utf-8"))
        self.minimal = json.loads((FIXTURE_DIR / "report_v1_minimal.json").read_text(encoding="utf-8"))

        steady_sample = filesystem_sample(self.state_dir)
        if steady_sample["available_bytes"] <= STEADY_RESUME_BYTES * 2:
            raise BaselineError("the temporary state directory has too little free space to measure a baseline")
        self.write_policy(enabled=True, pause=STEADY_PAUSE_BYTES, resume=STEADY_RESUME_BYTES)

        command([self.binary, "init", "--config", self.config_path], cwd=ROOT)
        command(
            [self.binary, "owner", "create", "--config", self.config_path, "--username", OWNER_USERNAME],
            input_text=OWNER_PASSWORD + "\n",
            cwd=ROOT,
        )
        # Enrollment Tokens are minted while the Server is stopped. A CLI write
        # racing the running Server corrupts the shared WAL index in
        # development mode, which is the deployment this baseline measures.
        tokens = [create_enrollment_token(self.binary, self.config_path) for _ in range(AGENT_COUNT)]
        self.start()
        self.cookie, self.csrf = login(self.client, OWNER_USERNAME, OWNER_PASSWORD)

        status, _, payload, _ = admin_post(
            self.client, self.cookie, self.csrf, "/api/admin/v1/networks", NETWORK
        )
        if status != 200:
            raise BaselineError(
                "Network registration failed with status " + str(status) + ": " + payload.decode("utf-8")[:400]
            )

        for agent_index, token in enumerate(tokens):
            self.agents.append(enroll_agent(token, self.client, agent_index))
        visible = agent_diagnostics(self.client, self.cookie)
        self.checks.append(Check("enrolled agents visible to the Server", AGENT_COUNT, len(visible)))

        self.stop()
        baseline = {
            "core": core_counts(self.db_path),
            "optional": optional_counts(self.db_path),
            "storage": storage_bytes(self.db_path),
        }
        self.start()

        steady = self.steady_phase(baseline)
        reads = steady["read_path"]
        mounted = mount_conditions(self.state_dir)
        sample_after = filesystem_sample(self.state_dir)
        pressure = self.pressure_phase(sample_after["available_bytes"])
        recovery = self.recovery_phase()
        self.stop()

        storage = storage_bytes(self.db_path)
        self.runtime_seconds = time.monotonic() - started_wall
        self.report = {
            "issue": 212,
            "story": 46,
            "generated_at": utc_now(),
            "run_root": str(self.run_root),
            "duration_seconds": round(self.runtime_seconds, 2),
            "seed": self.args.seed,
            "disclaimer": [
                "This is a measured baseline on one developer machine, not a production capacity guarantee.",
                "The optional history measured here is the existing generic optional metric writer "
                "(node_metric_samples, host_metric_samples). No other history family was implemented or measured.",
                "The 30 day precision-tier retention window described by the parent specification was not exercised: "
                "the baseline covers minutes of wall clock time, not a 30 day projection.",
            ],
            "conditions": {
                "hardware": hardware_conditions(),
                "mount": mounted,
                "filesystem_sample_at_start": steady_sample,
                "filesystem_sample_at_end": sample_after,
                "build": {
                    "binary": str(self.binary),
                    "bytes": file_bytes(self.binary),
                    "built_at": datetime.fromtimestamp(self.binary.stat().st_mtime, timezone.utc).strftime(
                        "%Y-%m-%dT%H:%M:%SZ"
                    ),
                    "profile": "debug",
                    "note": "A debug-profile build understates throughput; the report does not extrapolate it.",
                },
                "web_build_served": {
                    "web_root": str(self.web_root),
                    "index_built_at": datetime.fromtimestamp(
                        (self.web_root / "index.html").stat().st_mtime, timezone.utc
                    ).strftime("%Y-%m-%dT%H:%M:%SZ"),
                    "note": "The Server refuses to become ready without web assets; the served WebUI build is not "
                    "part of the capacity measurement.",
                },
                "cadence": {
                    "fast_path_seconds": self.args.interval,
                    "fast_path_agents": AGENT_COUNT,
                    "fast_path_nodes_per_agent": NODES_PER_AGENT,
                    "slow_scan_every_rounds": SLOW_SCAN_EVERY,
                    "slow_scan_carries": ["data_directory_size_bytes", "data_directory_capacity_bytes", "chain.peers"],
                    "capacity_sampling_seconds": FAST_SAMPLE_SECONDS,
                },
                "load_generator": {
                    "kind": "deterministic Reports submitted over the real Agent ingestion HTTP surface",
                    "seed": self.args.seed,
                    "substitution": "No live platpulse-agent process ran, so Agent-side collection cost is not measured.",
                },
                "database": {
                    "path": str(self.db_path),
                    "schema_version": sqlite_scalar(self.db_path, "SELECT MAX(version) FROM _sqlx_migrations"),
                },
            },
            "topology": {
                "agents": [{"agent_id": agent["agent_id"], "agent_epoch": agent["agent_epoch"]} for agent in self.agents],
                "nodes": [{"agent_index": index, "node_ids": ids} for index, ids in enumerate(self.node_ids)],
                "network": NETWORK,
            },
            "phases": {"steady": steady, "pressure": pressure, "recovery": recovery},
            "read_path": reads,
            "storage": storage,
            "storage_per_report_bytes": {
                "measured_at": "live readings taken while the Server was still running; a reading taken after "
                "the stop cannot see the WAL, because closing the last connection checkpoints it away.",
                "database_bytes_per_report": round(
                    (steady["storage_after"]["database_bytes"] - steady["storage_before"]["database_bytes"])
                    / max(1, steady["submissions"]),
                    2
                ),
                "wal_bytes_per_report": round(
                    (steady["storage_after"]["wal_bytes"] - steady["storage_before"]["wal_bytes"])
                    / max(1, steady["submissions"]),
                    2
                ),
                "wal_peak_bytes": steady["storage_peak"]["wal_bytes"],
                "database_peak_bytes": steady["storage_peak"]["database_bytes"],
                "after_shutdown": steady["storage_after_shutdown"],
            },
            "thresholds": {
                "steady_test_pause_bytes": STEADY_PAUSE_BYTES,
                "steady_test_resume_bytes": STEADY_RESUME_BYTES,
                "max_persisted_bytes": MAX_PERSISTED_BYTES,
                "rationale": [
                    "The Server invents no threshold: [capacity] enabled = true requires pause_below_bytes and "
                    "resume_above_bytes, so an operator must measure the deployment.",
                    "The steady-phase thresholds are deliberately small test values (1 GiB pause, 2 GiB resume) placed "
                    "roughly an order of magnitude below the mount free space, which keeps protection off while the "
                    "write path is measured: " + human_bytes(steady_sample["available_bytes"]) + " was available.",
                    "The pressure phase declares pause = resume = i64::MAX, the largest value the Server can persist "
                    "(CapacityConfig::MAX_PERSISTED_BYTES), so protection opens for any real mount while the "
                    "filesystem itself is never filled.",
                    "The recovery phase declares pause = resume = half of the measured free space, which is the "
                    "release the Server then records with reason 'resumed'.",
                ],
            },
            "not_delivered": [
                "No history family beyond the generic optional metric writer was built or measured.",
                "No 30 day retention or precision-tier downsampling was exercised; the visible gap evidence covers "
                "minutes, and upscaled old buckets were never produced.",
                "Agent-side collection was not measured: Reports were generated by the loader, not by a live "
                "platpulse-agent process, and validator hosts were not contacted.",
                "Only one mount, one filesystem and one writer path were measured; no multi-disk or network "
                "filesystem deployment was exercised.",
                "The Server ran in development mode without TLS and without a reverse proxy.",
                "A release-profile build was not measured.",
                "These items must be appended to this same report by a follow-up ticket; nothing here is a production "
                "guarantee.",
            ],
            "checks": [check.as_json() for check in self.checks],
        }
        return self.report


def write_json_report(report: dict, path: Path) -> None:
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_markdown_report(report: dict, path: Path) -> None:
    conditions = report["conditions"]
    steady = report["phases"]["steady"]
    pressure = report["phases"]["pressure"]
    recovery = report["phases"]["recovery"]
    lines = [
        "# Issue #212 Story 46: capacity and performance baseline",
        "",
        "Generated " + report["generated_at"] + " by scripts/capacity-baseline.py (seed " + str(report["seed"]) + ").",
        "",
        "## Declared conditions",
        "",
        "- Hardware: " + str(conditions["hardware"]["cpu_model"]) + ", " + str(conditions["hardware"]["cpu_cores"]) + " cores, " + human_bytes(conditions["hardware"]["memory_total_bytes"]) + " RAM, " + conditions["hardware"]["kernel"],
        "- Mount: " + str(conditions["mount"]["mount_point"]) + " (" + str(conditions["mount"]["filesystem_type"]) + ", source " + str(conditions["mount"]["mount_source"]) + ")",
        "- State directory free space at start: " + human_bytes(conditions["filesystem_sample_at_start"]["available_bytes"]) + " of " + human_bytes(conditions["filesystem_sample_at_start"]["total_bytes"]),
        "- Binary: " + conditions["build"]["binary"] + " (" + str(conditions["build"]["bytes"]) + " bytes, built " + conditions["build"]["built_at"] + ", " + conditions["build"]["profile"] + " profile)",
        "- Cadence: " + str(conditions["cadence"]["fast_path_agents"]) + " Agents x " + str(conditions["cadence"]["fast_path_nodes_per_agent"]) + " Nodes every " + str(conditions["cadence"]["fast_path_seconds"]) + "s; slow scan every " + str(conditions["cadence"]["slow_scan_every_rounds"]) + " rounds carrying data-directory and peer snapshots; capacity sampling every " + str(conditions["cadence"]["capacity_sampling_seconds"]) + "s",
        "",
        "## Steady write path",
        "",
        "| Measurement | Value |",
        "| --- | --- |",
        "| Rounds / submissions | " + str(steady["rounds"]) + " / " + str(steady["submissions"]) + " |",
        "| Wall duration | " + str(steady["duration_seconds"]) + "s |",
        "| Optional samples written | " + str(steady["observed_optional_samples"]) + " (expected " + str(steady["expected_optional_samples"]) + ") |",
        "| Host series / Node series | " + str(steady["optional_counts"]["host_series"]) + " / " + str(steady["optional_counts"]["node_series"]) + " |",
        "| Report latency p50 / p95 | " + str(steady["write_latency_ms"]["p50_ms"]) + "ms / " + str(steady["write_latency_ms"]["p95_ms"]) + "ms |",
        "| Database growth | " + human_bytes(steady["storage_after"]["database_bytes"] - steady["storage_before"]["database_bytes"]) + " |",
        "| Database / WAL after load (Server still running) | " + human_bytes(steady["storage_after"]["database_bytes"]) + " / " + human_bytes(steady["storage_after"]["wal_bytes"]) + " |",
        "| WAL peak during load | " + human_bytes(steady["storage_peak"]["wal_bytes"]) + " |",
        "| Database / WAL after shutdown | " + human_bytes(steady["storage_after_shutdown"]["database_bytes"]) + " / " + human_bytes(steady["storage_after_shutdown"]["wal_bytes"]) + " (the WAL is checkpointed away by the shutdown, so this is not the load's WAL) |",
        "| Core receipts | " + str(steady["core_counts"]["agent_report_receipts"]) + " |",
        "",
        "## Read path (p50 / p95)",
        "",
        "| Endpoint | Latency |",
        "| --- | --- |",
    ]
    for name, values in sorted(report["read_path"].items()):
        if "p50_ms" in values:
            lines.append("| " + values["path"] + " | " + str(values["p50_ms"]) + "ms / " + str(values["p95_ms"]) + "ms |")
        else:
            # Report a missing measurement truthfully instead of inventing a latency.
            lines.append("| " + values["path"] + " | not measured (status " + str(values["status"]) + ") |")
    lines += [
        "",
        "## Pressure, visible gap, recovery",
        "",
        "- Pressure pause floor: " + str(pressure["pause_below_bytes"]) + " bytes with " + human_bytes(pressure["mount_available_bytes"]) + " available; protected = " + str(pressure["capacity_after"]["protected"]),
        "- Reports accepted during pressure: " + str(pressure["core_counts_after"]["agent_report_receipts"]) + " receipts (was " + str(pressure["core_counts_before"]["agent_report_receipts"]) + ")",
        "- Optional samples during pressure: " + str(pressure["optional_counts_before"]["host_samples"] + pressure["optional_counts_before"]["node_samples"]) + " then " + str(pressure["optional_counts_after"]["host_samples"] + pressure["optional_counts_after"]["node_samples"]),
        "- Recorded gap: " + str(pressure["skipped_samples"]) + " skipped samples across " + str(len(pressure["skipped_series"])) + " series",
        "- Release floor: " + str(recovery["release_floor_bytes"]) + " bytes with " + human_bytes(recovery["mount_available_bytes"]) + " available; protected = " + str(recovery["capacity_after"]["protected"]),
        "- Interval closure: " + json.dumps([{k: row[k] for k in ("started_reason", "ended_reason")} for row in recovery["intervals"]]),
        "- Optional samples resumed: " + str(recovery["optional_counts_after"]["host_samples"] + recovery["optional_counts_after"]["node_samples"]) + " (was " + str(recovery["optional_counts_before"]["host_samples"] + recovery["optional_counts_before"]["node_samples"]) + ")",
        "",
        "## Self-checks",
        "",
        "| Check | Expected | Observed | OK |",
        "| --- | --- | --- | --- |",
    ]
    for check in report["checks"]:
        lines.append(
            "| " + check["name"] + " | " + str(check["expected"]) + " | " + str(check["observed"]) + " | "
            + ("yes" if check["ok"] else "NO") + " |"
        )
    lines += ["", "## Not delivered", ""]
    lines += ["- " + item for item in report["not_delivered"]]
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def parse_args(argv: list[str]):
    parser = argparse.ArgumentParser(description="Issue #212 Story 46 capacity and performance baseline")
    parser.add_argument("--output-root", type=Path, default=ROOT / "target/capacity-baseline")
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    parser.add_argument("--web-root", type=Path, default=ROOT / "platpulse-web/dist")
    parser.add_argument("--rounds", type=int, default=12, help="steady-phase rounds per Agent")
    parser.add_argument("--interval", type=float, default=5.0, help="steady-phase seconds between rounds")
    parser.add_argument("--pressure-rounds", type=int, default=3)
    parser.add_argument("--recovery-rounds", type=int, default=2)
    parser.add_argument("--query-samples", type=int, default=20)
    parser.add_argument("--seed", type=int, default=212)
    parser.add_argument("--skip-build", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    run = BaselineRun(args)
    try:
        report = run.run()
    except BaseException:
        # Never leave a Server process holding the temporary Server database.
        run.stop()
        raise
    json_path = run.run_root / "baseline.json"
    markdown_path = run.run_root / "baseline.md"
    write_json_report(report, json_path)
    write_markdown_report(report, markdown_path)
    failed = [check for check in report["checks"] if not check["ok"]]
    print("baseline written to " + str(run.run_root))
    print("  json:     " + str(json_path))
    print("  markdown: " + str(markdown_path))
    print("  checks:   " + str(len(report["checks"]) - len(failed)) + "/" + str(len(report["checks"])) + " ok")
    for check in failed:
        print("  FAILED: " + check["name"] + " expected " + str(check["expected"]) + " observed " + str(check["observed"]))
    steady = report["phases"]["steady"]
    print("  steady:   " + str(steady["submissions"]) + " reports in " + str(steady["duration_seconds"]) + "s, p95 "
          + str(steady["write_latency_ms"]["p95_ms"]) + "ms, " + str(steady["observed_optional_samples"]) + " optional samples")
    print("  pressure: " + str(report["phases"]["pressure"]["skipped_samples"]) + " skipped samples across "
          + str(len(report["phases"]["pressure"]["skipped_series"])) + " series")
    print("  recovery: protected=" + str(report["phases"]["recovery"]["capacity_after"]["protected"]))
    return 1 if failed else 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except BaselineError as error:
        print("baseline failed: " + str(error), file=sys.stderr)
        sys.exit(2)
